//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaToContract
    {
        public int id { get; set; }
        public int contractID { get; set; }
        public int areaID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Contract Contract { get; set; }
    }
}
