//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int id { get; set; }
        public string bas { get; set; }
        public double price { get; set; }
        public int areaID { get; set; }
        public bool travelTrip { get; set; }
        public int userID { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> fFinalAmountID { get; set; }
        public Nullable<int> fContractID { get; set; }
        public Nullable<bool> contractType { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual User User { get; set; }
        public virtual FinalAmount FinalAmount { get; set; }
        public virtual FinalAmount FinalAmount1 { get; set; }
    }
}
