//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardTbl()
        {
            this.TransitTbls = new HashSet<TransitTbl>();
        }
    
        public int id { get; set; }
        public string describe { get; set; }
        public Nullable<double> freeMonthly { get; set; }
        public Nullable<double> freeWeekly { get; set; }
        public Nullable<double> freeDaily { get; set; }
        public double single { get; set; }
        public string test { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitTbl> TransitTbls { get; set; }
    }
}
