//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalAmount
    {
        public int id { get; set; }
        public Nullable<double> finalAmount1 { get; set; }
        public Nullable<int> fUserID { get; set; }
        public Nullable<System.DateTime> monthDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
