//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RavKavEntities : DbContext
    {
        public RavKavEntities()
            : base("name=RavKavEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AreaToContract> AreaToContracts { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<FinalAmount> FinalAmounts { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VertificationCode> VertificationCodes { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> sp_vretificationCode_Insert(Nullable<int> fUserID)
        {
            var fUserIDParameter = fUserID.HasValue ?
                new ObjectParameter("fUserID", fUserID) :
                new ObjectParameter("fUserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_vretificationCode_Insert", fUserIDParameter);
        }
    
        public virtual int Area_Insert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Area_Insert");
        }
    
        public virtual int AreaToContract_Insert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AreaToContract_Insert");
        }
    
        public virtual int AreaToContract_Insert_V2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AreaToContract_Insert_V2");
        }
    
        public virtual int Contract_Insert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Contract_Insert");
        }
    
        public virtual ObjectResult<sp_travel_Order_Result> sp_travel_Order()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_travel_Order_Result>("sp_travel_Order");
        }
    }
}
