//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transit
    {
        public int id { get; set; }
        public string bas { get; set; }
        public double price { get; set; }
        public int areaID { get; set; }
        public bool InternalOrIntermediate { get; set; }
        public bool transitTrip { get; set; }
        public int userID { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
