//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelsTbl
    {
        public int id { get; set; }
        public System.DateTime dateAndTime { get; set; }
        public int userId { get; set; }
        public int TransitId { get; set; }
        public string Property1 { get; set; }
        public string Property2 { get; set; }
    
        public virtual TransitTbl TransitTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
