//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VertificationCode
    {
        public int id { get; set; }
        public string verificationCode { get; set; }
        public Nullable<int> fUserID { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public VertificationCode(int id)
        {
            this.fUserID = id;
        }
    }
}
